import { Check } from "lucide-react";
import { createCheckoutSession } from "@/lib/billing/actions";
import { Badge, Panel } from "@/components/ui";

const tiers = [
  { name: "FREE", priceMonthly: "0 €", description: "Pour découvrir votre couverture.", features: ["1 audit public", "Mesure ponctuelle", "Lecture de la couverture"], action: "Créer un compte gratuit", priceId: null },
  { name: "SOLO", priceMonthly: "29 €", description: "Pour une marque suivie avec précision.", features: ["1 marque suivie", "15 requêtes", "Audit hebdomadaire", "Correctifs de contenu"], action: "Commencer avec Solo", priceId: process.env.STRIPE_PRICE_SOLO },
  { name: "PRO", priceMonthly: "49 €", description: "Le cockpit GEO pour les équipes exigeantes.", features: ["3 marques suivies", "50 requêtes par marque", "Audit bi-hebdomadaire", "Sources et export CSV"], action: "Passer Pro", priceId: process.env.STRIPE_PRICE_PRO, mostPopular: true },
  { name: "SCALE", priceMonthly: "79 €", description: "Pour instrumenter une croissance multi-marques.", features: ["10 marques suivies", "100 requêtes par marque", "Audit quotidien", "Support prioritaire"], action: "Passer Scale", priceId: process.env.STRIPE_PRICE_SCALE },
];

export default function PricingPage() {
  return <main className="min-h-screen bg-paper px-6 py-16 text-ink sm:py-24"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-2xl text-center"><Badge tone="signal">Tarifs</Badge><h1 className="mt-5 text-5xl">Un instrument clair pour une présence durable.</h1><p className="mt-5 text-lg leading-8 text-muted">Commencez par mesurer. Passez à l’action quand le signal est établi.</p></div><div className="mt-14 grid gap-4 lg:grid-cols-4">{tiers.map((tier) => <Panel key={tier.name} className={`flex flex-col p-6 ${tier.mostPopular ? "border-cited bg-ink text-paper" : ""}`}><div className="flex items-center justify-between"><h2 className="font-heading text-lg">{tier.name}</h2>{tier.mostPopular && <Badge tone="cited">Recommandé</Badge>}</div><p className={`mt-4 text-sm leading-6 ${tier.mostPopular ? "text-paper/70" : "text-muted"}`}>{tier.description}</p><div className="mt-8 font-heading text-4xl">{tier.priceMonthly}<span className={`text-sm font-normal ${tier.mostPopular ? "text-paper/60" : "text-muted"}`}> / mois</span></div><form action={async () => { "use server"; if (tier.name !== "FREE") await createCheckoutSession(tier.name); }} className="mt-7"><button type="submit" disabled={!tier.priceId && tier.name !== "FREE"} className={`w-full rounded-md px-4 py-3 font-heading text-sm font-semibold transition-colors disabled:cursor-not-allowed disabled:opacity-50 ${tier.mostPopular ? "bg-paper text-ink hover:bg-cited-light" : "bg-cited text-white hover:bg-ink"}`}>{tier.action}</button></form><ul className={`mt-8 space-y-3 text-sm ${tier.mostPopular ? "text-paper/80" : "text-muted"}`}>{tier.features.map((feature) => <li key={feature} className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-cited" />{feature}</li>)}</ul></Panel>)}</div></div></main>;
}
